# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
# - main

strategy:
  matrix:
    macos10.14:
      imageName: 'macOS-10.14'
    macos10.15:
      imageName: 'macOS-10.15'

pool:
  vmImage: $(imageName)

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    which brew
    echo "aabbcc" > $(Build.ArtifactStagingDirectory)/aa.txt
    touch $(Build.ArtifactStagingDirectory)/$(sw_vers -productVersion).rr
  displayName: 'Run a multi-line script'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    publishLocation: 'pipeline'
# - task: GitHubRelease@1
#  inputs:
#    gitHubConnection: github.com_railwaycat
#    repositoryName: '$(Build.Repository.Name)'
#    action: 'create' # Options: create, edit, delete
#    target: '$(Build.SourceVersion)' # Required when action == Create || Action == Edit
#    tagSource: userSpecifiedTag # Required when action == Create# Options: auto, manual
#    tag: $(Build.BuildNumber)
#    assets: '$(Build.ArtifactStagingDirectory)/aa.txt'
#    isDraft: true # Optional
