# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: macOS-10.14

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    which brew
    brew info gnutls
    echo "aabbcc" > aa.txt
  displayName: 'Run a multi-line script'

- task: GitHubRelease@1
  inputs:
    gitHubConnection: github.com_railwaycat
    repositoryName: '$(Build.Repository.Name)'
    action: 'create' # Options: create, edit, delete
    target: '$(Build.SourceVersion)' # Required when action == Create || Action == Edit
    tagSource: 'gitTag' # Required when action == Create# Options: auto, manual
    assets: $(Build.ArtifactStagingDirectory)/aa.txt
    isDraft: true # Optional
